# Generated by Django 3.0 on 2019-12-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(upload_to='store/'),
        ),
    ]
