# Generated by Django 3.0 on 2020-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='pic',
            field=models.ImageField(upload_to='background/store/'),
        ),
    ]
