# Generated by Django 3.0 on 2019-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='pic',
            field=models.ImageField(upload_to='background/home/'),
        ),
    ]
